# Generated by Django 4.1.7 on 2023-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_alter_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(default=list, to='MainSite.skill'),
        ),
    ]
