# Generated by Django 4.1.8 on 2023-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0007_group_student_group_student_hide_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_book',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram',
            field=models.CharField(default='', max_length=255),
        ),
    ]
