# Generated by Django 4.1.8 on 2023-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0008_alter_student_record_book_alter_student_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_book',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
