# Generated by Django 4.1.8 on 2023-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0010_alter_student_record_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
